# Generated by Django 2.0.7 on 2018-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bizname', models.CharField(max_length=200)),
                ('Location', models.TextField()),
                ('Phone', models.CharField(max_length=14)),
            ],
        ),
    ]
