# Generated by Django 2.0.7 on 2019-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190406_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
    ]
